### ISSUE TITLE
'com.paypal.pyplcheckout.data.model.pojo.Email com.paypal.pyplcheckout.data.model.pojo.Buyer.getEmail()' on a null object reference

### ISSUE THREAD

**Issue by ehangwork** [harrowmykel/flutter_paypal_native#28]
exception in parsing URI in onNewIntent in InitiateCheckoutActivity Attempt to invoke virtual method 'com.paypal.pyplcheckout.data.model.pojo.Email com.paypal.pyplcheckout.data.model.pojo.Buyer.getEmail()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'com.paypal.pyplcheckout.data.model.pojo.Email com.paypal.pyplcheckout.data.model.pojo.Buyer.getEmail()' on a null object reference
	at com.piccmaq.flutter_paypal_native.models.approvaldata.PPEmail.fromPaypalObject(PPEmail.java:24)
	at com.piccmaq.flutter_paypal_native.models.approvaldata.PPPayer.fromPayPalObject(PPPayer.java:58)
	at com.piccmaq.flutter_paypal_native.models.approvaldata.PPApprovalData.fromPayPalObject(PPApprovalData.java:34)
	at com.piccmaq.flutter_paypal_native.models.PayPalCallBackHelper.onPayPalApprove(PayPalCallBackHelper.java:29)
	at com.piccmaq.flutter_paypal_native.FlutterPaypalNativePlugin.lambda$initialisePaypalConfig$0$com-piccmaq-flutter_paypal_native-FlutterPaypalNativePlugin(FlutterPaypalNativePlugin.java:130)
	at com.piccmaq.flutter_paypal_native.FlutterPaypalNativePlugin$$ExternalSyntheticLambda1.onApprove(Unknown Source:2)
	at com.paypal.pyplcheckout.ui.utils.PYPLCheckoutUtils.approveAndReturnFallbackFlow(PYPLCheckoutUtils.kt:958)
	at com.paypal.pyplcheckout.ui.utils.PYPLCheckoutUtils.approveAndReturn(PYPLCheckoutUtils.kt:863)
	at com.paypal.pyplcheckout.ui.utils.PYPLCheckoutUtils.returnToMerchant(PYPLCheckoutUtils.kt:813)
	at com.paypal.pyplcheckout.ui.utils.PYPLCheckoutUtils.returnToProvider(PYPLCheckoutUtils.kt:671)
	at com.paypal.pyplcheckout.ui.feature.home.activities.PYPLInitiateCheckoutActivity.returnFromApproval(PYPLInitiateCheckoutActivity.kt:254)
	at com.paypal.pyplcheckout.ui.feature.home.activities.PYPLInitiateCheckoutActivity.onNewIntent(PYPLInitiateCheckoutActivity.kt:240)
	at android.app.Activity.performNewIntent(Activity.java:8613)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1556)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1569)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3962)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3969)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

支付完成后，数据处理有一处非空没有判断

**代码位置在 PPEmail ， 外部传入的Buyer 可能为null**

 public static PPEmail fromPaypalObject(Buyer buyer){
        PPEmail n=new PPEmail();
        if (buyer.getEmail() == null) {
            return n;
        }
        n.setValue(buyer.getEmail().getStringValue());
        return n;
    }

麻烦修复下

**Comment by harrowmykel** [comment]
fixed

**Comment by ehangwork** [comment]
excellent! Thank you!
