### ISSUE TITLE
Initi failing with: Unterminated string at character 57

### ISSUE THREAD

**Issue by timobure** [harrowmykel/flutter_paypal_native#34]
This error appears on initialization only on release builds. Debug build runs just fine:

**Environment:**

- Flutter: 3.19.4
- Dart: 3.3.2
- ext.kotlin_version: 1.9.22

```
FATAL EXCEPTION: main
E/AndroidRuntime(20834): Process: io.poola.app, PID: 20834
E/AndroidRuntime(20834): rm.b: Unterminated string at character 57
E/AndroidRuntime(20834):        at rm.e.h(Unknown Source:21)
E/AndroidRuntime(20834):        at rm.e.f(SourceFile:14)
E/AndroidRuntime(20834):        at rm.e.g(SourceFile:15)
E/AndroidRuntime(20834):        at rm.c.<init>(SourceFile:14)
E/AndroidRuntime(20834):        at rm.c.<init>(SourceFile:24)
E/AndroidRuntime(20834):        at com.paypal.pyplcheckout.data.api.calls.CancelUrlApi.createService(SourceFile:5)
E/AndroidRuntime(20834):        at com.paypal.pyplcheckout.data.api.BaseApi.enqueueRequest(SourceFile:6)
E/AndroidRuntime(20834):        at com.paypal.pyplcheckout.data.repositories.Repository.fetchCancelURL(Unknown Source:12)
E/AndroidRuntime(20834):        at com.paypal.checkout.PayPalCheckout$handleLaunchOrder$1.invoke(SourceFile:3)
E/AndroidRuntime(20834):        at com.paypal.checkout.PayPalCheckout$handleLaunchOrder$1.invoke(SourceFile:1)
E/AndroidRuntime(20834):        at com.paypal.checkout.createorder.CreateOrderActions$createOrder$1.invokeSuspend(SourceFile:15)
E/AndroidRuntime(20834):        at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:4)
E/AndroidRuntime(20834):        at kotlinx.coroutines.b1.run(SourceFile:18)
E/AndroidRuntime(20834):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(20834):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20834):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(20834):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(20834):        at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(20834):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20834):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/AndroidRuntime(20834):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(20834):        Suppressed: kotlinx.coroutines.z0: [w2{Cancelling}@2b1b4ca, Dispatchers.Main]
```

**Comment by harrowmykel** [comment]
Does this work now?
